config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  get 'events/new', to: 'events#new', as: 'events'
  post 'events/new', to: 'events#create'
  get 'events/show/:id/', to: 'events#show', as: 'event_show'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'singout', to: 'sessions#destroy'
  get 'users/new', to: 'users#new', as: 'users'
  post 'users/new', to: 'users#create'
  get 'users/show'
  post 'attend', to: 'events#attend_event'
  delete 'attend', to: 'events#unattend_event'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creator.rb
class Creator < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_qries
  belongs_to :creator, class_name: 'User'
  scope :previous, -> { where('event_date < ?', Time.zone.now) }
  scope :future, -> { where('event_date >= ?', Time.zone.now) }

  validates :location, presence: true
  validates :event_date, presence: true
  validates :description, presence: true
end

app/models/event_qry.rb
class EventQry < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :event_qries
  has_many :events, foreign_key: :creator_id

  before_create do
    self.token = @token
  end

  def token_generator
    temp = SecureRandom.urlsafe_base64
    temp = Digest::SHA1.hexdigest temp
    @token = temp
  end

  validates :name, length: { minimum: 3 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include SessionsHelper
  def new
    redirect_to root_path if current_user.nil?
    @event = Event.new
  end

  def index
    @past_events = Event.previous
    @present_events = Event.future
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      current_user.event_qries.create(event_id: @event.id)
      redirect_to root_path
    else
      respond_to do |f|
        f.html { render :new }
        f.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @event = Event.find(params[:id])
    @attending = @event.event_qries
  end

  def attend_event
    creator = EventQry.new(user_id: current_user.id, event_id: params[:event_id])
    redirect_to request.referrer if creator.save
  end

  def unattend_event
    creators = current_user.event_qries.where(event_id: params[:event_id]).first
    redirect_to request.referrer if creators.destroy
  end

  def event_params
    params.require(:event).permit(:location, :event_date, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery with: :exception
  include SessionsHelper
  def new
    redirect_to users_show_path unless current_user.nil?
  end

  def create
    user = User.find_by_name(params[:session][:name])
    if user.nil?
      flash[:danger] = []
      flash.now[:danger] << 'Invalid name' unless params[:session][:name].split.empty?
      flash.now[:danger] << 'Name can not be blank' if params[:session][:name].split.empty?
      render 'new'
    else
      log_in user
      remember user
      redirect_to root_path
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      remember @user
      redirect_to root_path
    else
      respond_to do |f|
        f.html { render :new }
        f.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    if current_user.nil?
      (redirect_to login_path)
    else
      @past_events = current_user.events.previous
      @present_events = current_user.events.future
      @attending = current_user.event_qries
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def user_attending?
    !EventQry.find_by(user_id: current_user.id, event_id: @event.id).nil?
  end

  def event(attend)
    @event = attend.event
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.update(token: @token)
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:token] = user.token
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    cookies.delete(:token)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_assitance.html.erb
<% if @event.event_date >= DateTime.now %>
<% unless current_user.nil? || @event.creator_id == current_user.id%>
	<%= link_to 'Attend', attend_path(:event_id => @event.id), method: :post unless user_attending?%>
	<%= link_to 'Un-Attend', attend_path(:event_id => @event.id), method: :delete if user_attending?%>
<% end %>
<% end %>

app/views/events/_errors.html.erb
<% if @event.errors.any? %>
	<% @event.errors.full_messages.each do |e| %>
		<li><%= e %></li>
	<% end %>
	<br>
	<br>
<% end %>

app/views/events/_form.html.erb
<%= form_for @event do |event| %>
	<%= event.label :name, :value => current_user.name%>
	<br>
	<%= event.text_field :location, :placeholder => 'Location'%>
	<br>
	<%= event.text_field :description, :placeholder => 'description'%>
	<br>
	<%= event.date_field :event_date %>
	<br>
	<%= event.submit 'submit' %>
<%end%>

app/views/events/_show_form.html.erb
<h1>Event Description</h1>
<p>Ower: <%= User.find(@event.creator_id).name %> </p>
<p>Description: <%= @event.description%></p>
<p>Location: <%= @event.location%></p>
<p>Date: <%= @event.event_date%></p>
<h2>Attending</h2>
<ul>
	<% @attending.each do |user| %>
		<li><%= User.find(user.user_id).name %></li>
	<% end %>
</ul>

app/views/events/index.html.erb
<h1>All Events</h1>
<%= render 'users/events', event: @event %>

app/views/events/new.html.erb
<h1>New Events</h1>
<%= render 'errors', event: @event %>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<%= render 'show_form', event: @event %>
<%= render 'assitance', event: @event %>

app/views/layouts/_header.html.erb
<header>
	<nav>
		<ul>
			<% unless current_page?(root_path) %>
				<li><%= link_to 'Home', root_path  %></li>
			<% end %>
			<% unless current_page?(users_show_path) || current_user.nil? %>
				<li><%= link_to 'My Events', users_show_path  %></li>
			<% end %>
		</ul>
	</nav>
	<% unless current_user.nil? %>
		Welcome <%= current_user.name.to_s  %>
		<br>
		<%= link_to 'Log out', singout_path, method: :delete, data: {confirm: 'Are you sure ?'} %>
		<br>
		<%= link_to 'New event', events_new_path unless  current_page?(events_new_path) %>
	<% else %>
		<%= link_to 'Log in', login_path unless current_page?(login_path)%>
		<br>
		<%= link_to 'Sing Up', users_path unless current_page?(users_path) %>
	<% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/header' %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_attending.html.erb
<h3>Up-Comming Events</h3>
<% @attending.each do |attending| %>
	<%event(attending)%>
	<% if @event.event_date >= DateTime.now %>
		<li>Owner: <%= User.find_by_id(@event.creator_id).name %></li>
		<li>Location: <%= @event.location %></li>
		<li>Date: <%= @event.event_date %></li>
		<%= render 'events/assitance', event: @event %>
	<% end %>
<% end %>
<% unless !@past_events.nil? %>
	<h3>Past Events</h3>
<% end %>
<% @attending.each do |attending| %>
	<%event(attending)%>
	<% if @event.event_date < DateTime.now %>
		<li>Owner: <%= User.find_by_id(@event.creator_id).name %></li>
		<li>Location: <%= @event.location %></li>
		<li>Date: <%= @event.event_date %></li>
	<% end %>
<% end %>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
	<% @user.errors.full_messages.each do |e| %>
		<li><%= e %></li>
	<% end %>
<% end %>

app/views/users/_events.html.erb
<h1><%= 'Events to Come'%></h1>
<% @present_events.each do |e| %>
	<% @event = e %>
	<ul>
		<li>Owner: <%= User.find_by_id(e.creator_id).name %></li>
		<li>Location: <%= e.location %></li>
		<li>Date: <%= e.event_date %></li>
		<%= link_to 'More Info', event_show_path(e)%>
		<%= render 'events/assitance', event: @event %>
	</ul>
<% end %>
<br>
<br>
<h1><%= 'Pasts Events'%></h1> 
<% @past_events.each do |e| %>
	<ul>
		<li>Owner: <%= User.find_by_id(e.creator_id).name %></li>
		<li>Location: <%= e.location %></li>
		<li>Date: <%= e.event_date %></li>
		<%= link_to 'More Info', event_show_path(e)%>
	</ul>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |user| %>
	<%= user.text_field :name, :placeholder => 'name' %>
	<%= user.submit 'submit' %>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<%= render 'errors' %>
<%= render 'form', post: @user %>

app/views/users/show.html.erb
<h1>Users Events</h1>
<%= render 'events' %>
<%= render 'attending' %>